services:
  db:
    image: postgres:16
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${SPRING_DATASOURCE_PASSWORD:?SPRING_DATASOURCE_PASSWORD var is required in .env file}
      POSTGRES_USER: pharmacy_app
      POSTGRES_DB: pharmacy_db

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/db/init:/docker-entrypoint-initdb.d

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U pharmacy_app -d pharmacy_db" ]
      interval: 5s
      timeout: 5s
      retries: 5


  backend:
    env_file:
      - .env
    build: backend
    container_name: spring_app
    depends_on:
      db:
        condition: service_healthy

    volumes:
      - ./media:/app/media


    restart: unless-stopped

    environment:
      DB_HOST: db
      DB_PORT: 5432
      SPRING_DATASOURCE_USERNAME: pharmacy_app
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD:?SPRING_DATASOURCE_PASSWORD var is required in .env file}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY:?JWT_SECRET_KEY var is required in .env file}
      SPRING_ADMIN_LOGIN: ${SPRING_ADMIN_LOGIN:?SPRING_ADMIN_LOGIN var is required in .env file}
      SPRING_ADMIN_PASSWORD: ${SPRING_ADMIN_PASSWORD:?SPRING_ADMIN_PASSWORD var is required in .env file}
      MEDIA_PATH: /app/media/
      ALLOWED_ORIGINS: http://localhost:8080


  frontend:
    build: frontend
    container_name: frontend_app
    depends_on:
      - backend
    ports:
      - "8080:80"
    restart: unless-stopped

  mailserver:
    image: ghcr.io/docker-mailserver/docker-mailserver:latest
    container_name: mailserver
    hostname: mail
    domainname: chebupitsa.ru

    env_file:
      - ./smtp/mailserver.env

    ports: # ничего из этого не понял, но на всякий подписал
      - "25:25" # SMTP
      - "80:80" # let's encrypt
      - "143:143" # IMAP
      - "443:443" # https?
      - "465:465" # SMTPS
      - "587:587" # Submission
      - "993:993" # IMAPS

    volumes:
      - ./smtp/mail-data/:/var/mail/
      - ./smtp/mail-state/:/var/mail-state/
      - ./smtp/mail-logs/:/var/log/mail/
      - ./smtp/config/:/tmp/docker-mailserver/
      - /etc/letsencrypt/:/etc/letsencrypt:ro
      - mail-queue:/var/spool/postfix


    restart: always
    stop_grace_period: 1m

    healthcheck:
      test: "ss --listening --ipv4 --tcp | grep --silent ':smtp' || exit 1"
      timeout: 3s
      retries: 1

volumes:
  postgres_data:
  mail-queue: