spring.application.name=diploma_new_pharmacy

spring.datasource.url=jdbc:postgresql://localhost:5433/pharmacy_db
spring.datasource.username=pharmacy_app
spring.datasource.password=${PHARMACY_DB_PASSWORD}
#spring.datasource.email=postgres
#spring.datasource.password=${PHARMACY_DB_ROOT_PASSWORD}


spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#logging.level.org.springframework=INFO
logging.level.org.springframework=DEBUG

spring.flyway.default-schema=flyway
spring.flyway.schemas=pharmacy

jwt.secret=${JWT_SECRET_KEY}

# minutes
jwt.access-token-ttl=5

# days
jwt.refresh-token-ttl=30

guest.cookie.ttl=30
guest.cookie.name=guestCartId

app.bootstrap-admin.email=${SPRING_ADMIN_LOGIN}
app.bootstrap-admin.password=${SPRING_ADMIN_PASSWORD}

# project root for now
media.path = media/


