spring.application.name=diploma_new_pharmacy

spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5434}/pharmacy_db
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.format_sql=true
server.port=8080

logging.level.org.springframework=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.org.beatrice.diploma_new_pharmacy=DEBUG

spring.flyway.default-schema=flyway
spring.flyway.schemas=pharmacy

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

jwt.secret=${JWT_SECRET_KEY}

# minutes
jwt.access-token-ttl=5

# days
jwt.refresh-token-ttl=30

guest.cookie.name=guestCartId

app.bootstrap-admin.email=${SPRING_ADMIN_LOGIN}
app.bootstrap-admin.password=${SPRING_ADMIN_PASSWORD}

# project root for now
media.path = /app/media/


